language: node_js
cache: yarn
node_js:
  - lts/*
  - '8.12'
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: coverage
      node_js: '8.12'
      script:
        - 'bash <(curl -s https://codecov.io/bash)'
    - stage: release
      node_js: '8.12'
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
